In [9]:
import numpy as np

def lh_factorization(A):
    """
    LH факторизація матриці A.
    Повертає нижньотрикутню матрицю L і верхньотрикутню матрицю H.
    """
    n = A.shape[0]
    L = np.eye(n)  # Ініціалізуємо L як одиничну матрицю
    H = np.zeros((n, n))  # Ініціалізуємо H нулями

    for i in range(n):
        # Заповнюємо L та H на основі і-го рядка та стовпця матриці A
        for j in range(i + 1):
            L[i, j] = A[i, j] - np.dot(L[i, :j], H[:j, j])
        for j in range(i, n):
            H[i, j] = (A[i, j] - np.dot(L[i, :i], H[:i, j])) / L[i, i]
            
        # Виводимо проміжний результат
        print(f"Ітерація {i + 1}:")
        print("L матриця:")
        print(L)
        print("\nH матриця:")
        print(H)
        print("-------------------------------")

    return L, H

def multiply_LH(L, H):
    """Множення матриць L та H."""
    return np.dot(L, H)

# Приклад використання
A = np.array([[49.0, 42.0, 28.0], [42.0, 61.0, 39.0], [28.0, 39.0, 29.0]])
L, H = lh_factorization(A)
print("L матриця:")
print(L)
print("\nH матриця:")
print(H)

# Множення матриць L та H
result = multiply_LH(L, H)

print("\nПеревірка множенням L * H:")
print(result)
print("\nПочаткова матриця A:")
print(A)

Ітерація 1:
L матриця:
[[49.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

H матриця:
[[1.         0.85714286 0.57142857]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
-------------------------------
Ітерація 2:
L матриця:
[[49.  0.  0.]
 [42. 25.  0.]
 [ 0.  0.  1.]]

H матриця:
[[1.         0.85714286 0.57142857]
 [0.         1.         0.6       ]
 [0.         0.         0.        ]]
-------------------------------
Ітерація 3:
L матриця:
[[49.  0.  0.]
 [42. 25.  0.]
 [28. 15.  4.]]

H матриця:
[[1.         0.85714286 0.57142857]
 [0.         1.         0.6       ]
 [0.         0.         1.        ]]
-------------------------------
L матриця:
[[49.  0.  0.]
 [42. 25.  0.]
 [28. 15.  4.]]

H матриця:
[[1.         0.85714286 0.57142857]
 [0.         1.         0.6       ]
 [0.         0.         1.        ]]

Перевірка множенням L * H:
[[49. 42. 28.]
 [42. 61. 39.]
 [28. 39. 29.]]

Початкова матриця A:
[[49. 42. 28.]
 [42. 61. 39.]
 [28. 39. 29.]]
